name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      - name: Install lcov
        run: sudo apt-get install -y lcov 

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          ./text_restricter_tests
          ./text_restricter_static_tests

      - name: Generate coverage
        run: |
          lcov -c -d . --include "*/strategies/*.h" --include "*/tests/*.cpp" --output-file coverage.info
          lcov --remove coverage.info "*usr/include*" "*gtest*" --output-file coverage_filtered.info

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }} 
            path-to-lcov: ${{ github.workspace }}/coverage/lcov.info