name: Release

on:
  push:
    tags:
      - 'v*'  # Только для тегов, начинающихся с 'v' (например, v1.0.0)

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg cmake build-essential g++ libgtest-dev

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ./text_restricter_tests
          ./text_restricter_static_tests

      - name: Create .deb package
        run: |
          cd build
          cpack -G DEB

      - name: Create GitHub Release and Upload .deb Package
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
